# Generated by Django 4.2 on 2023-07-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('line', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='team_images', verbose_name='главная фотография')),
                ('corporate_structure_picture', models.ImageField(blank=True, null=True, upload_to='team_images', verbose_name='фотография структуры')),
            ],
            options={
                'verbose_name_plural': 'страница команды',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=556, null=True, verbose_name='отдел')),
                ('department_ru', models.CharField(blank=True, max_length=556, null=True, verbose_name='отдел')),
                ('department_ky', models.CharField(blank=True, max_length=556, null=True, verbose_name='отдел')),
                ('department_en', models.CharField(blank=True, max_length=556, null=True, verbose_name='отдел')),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='line_images', verbose_name='главная фотография')),
                ('name', models.CharField(max_length=556, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=556, null=True, verbose_name='ФИО')),
                ('name_ky', models.CharField(max_length=556, null=True, verbose_name='ФИО')),
                ('name_en', models.CharField(max_length=556, null=True, verbose_name='ФИО')),
                ('status', models.CharField(max_length=556, verbose_name='должность')),
                ('status_ru', models.CharField(max_length=556, null=True, verbose_name='должность')),
                ('status_ky', models.CharField(max_length=556, null=True, verbose_name='должность')),
                ('status_en', models.CharField(max_length=556, null=True, verbose_name='должность')),
                ('experience', models.TextField(verbose_name='опыт работы')),
                ('experience_ru', models.TextField(null=True, verbose_name='опыт работы')),
                ('experience_ky', models.TextField(null=True, verbose_name='опыт работы')),
                ('experience_en', models.TextField(null=True, verbose_name='опыт работы')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='company.company', verbose_name='компания')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='line.line', verbose_name='напрвление')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
    ]
