# Generated by Django 4.2 on 2023-06-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('line', '0003_alter_extrafields_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='team_images', verbose_name='главная фотография')),
                ('corporate_structure_picture', models.ImageField(blank=True, null=True, upload_to='team_images', verbose_name='фотография структуры')),
            ],
            options={
                'verbose_name_plural': 'страница команды',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=556, null=True, verbose_name='отдел')),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='line_images', verbose_name='главная фотография')),
                ('name', models.CharField(max_length=556, verbose_name='имя фамилие')),
                ('status', models.CharField(max_length=556, verbose_name='должность')),
                ('experience', models.TextField(verbose_name='опыт работы')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='line.line', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
    ]
