# Generated by Django 4.2 on 2023-07-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(max_length=255, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status_en',
            field=models.CharField(max_length=255, null=True, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='должность'),
        ),
    ]
