# Generated by Django 4.2 on 2023-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_team_name_alter_team_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='main_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='line_images', verbose_name='главная фотография'),
        ),
    ]
