# Generated by Django 4.2 on 2023-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_team_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department_en',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='отдел'),
        ),
        migrations.AddField(
            model_name='team',
            name='department_ky',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='отдел'),
        ),
        migrations.AddField(
            model_name='team',
            name='department_ru',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='отдел'),
        ),
        migrations.AddField(
            model_name='team',
            name='experience_en',
            field=models.TextField(null=True, verbose_name='опыт работы'),
        ),
        migrations.AddField(
            model_name='team',
            name='experience_ky',
            field=models.TextField(null=True, verbose_name='опыт работы'),
        ),
        migrations.AddField(
            model_name='team',
            name='experience_ru',
            field=models.TextField(null=True, verbose_name='опыт работы'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=556, null=True, verbose_name='имя фамилие'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ky',
            field=models.CharField(max_length=556, null=True, verbose_name='имя фамилие'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=556, null=True, verbose_name='имя фамилие'),
        ),
        migrations.AddField(
            model_name='team',
            name='status_en',
            field=models.CharField(max_length=556, null=True, verbose_name='должность'),
        ),
        migrations.AddField(
            model_name='team',
            name='status_ky',
            field=models.CharField(max_length=556, null=True, verbose_name='должность'),
        ),
        migrations.AddField(
            model_name='team',
            name='status_ru',
            field=models.CharField(max_length=556, null=True, verbose_name='должность'),
        ),
    ]
