# Generated by Django 4.2 on 2023-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_team_department_en_team_department_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=556, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=556, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_ky',
            field=models.CharField(max_length=556, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=556, null=True, verbose_name='ФИО'),
        ),
    ]
