# Generated by Django 4.2 on 2023-08-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_team_main_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
    ]
