# Generated by Django 4.2 on 2023-07-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0005_extrafields_description_en_and_more'),
        ('staff', '0005_alter_team_name_alter_team_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='line.line', verbose_name='напрвление'),
        ),
    ]
