# Generated by Django 4.2 on 2023-09-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_team_main_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='отдел')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'отделы',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_department', to='staff.department', verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_department', to='staff.department', verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_department', to='staff.department', verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_department', to='staff.department', verbose_name='отдел'),
        ),
    ]
