# Generated by Django 4.2 on 2023-09-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0007_alter_extrafields_options'),
        ('staff', '0007_department_alter_team_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department_en',
        ),
        migrations.RemoveField(
            model_name='team',
            name='department_ky',
        ),
        migrations.RemoveField(
            model_name='team',
            name='department_ru',
        ),
        migrations.AddField(
            model_name='department',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_lines', to='line.line', verbose_name='напрвление'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_department', to='staff.department', verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='team',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lines', to='line.line', verbose_name='напрвление'),
        ),
    ]
