# Generated by Django 4.2 on 2023-07-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('name_ky', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='название')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='название')),
                ('title_ky', models.CharField(blank=True, max_length=256, null=True, verbose_name='название')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('content_ky', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='картинка поста')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_categories', to='news.postcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
