# Generated by Django 4.2 on 2023-06-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Новости компании', 'Новости компании'), ('Пресс-релизы', 'Пресс-релизы'), ('События', 'События'), ('Галерея', 'Галерея')], max_length=20, null=True, verbose_name='категория')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='картинка поста')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
