# Generated by Django 4.2 on 2023-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ky',
            field=models.TextField(blank=True, null=True, verbose_name='контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ky',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='название'),
        ),
    ]
