# Generated by Django 4.2 on 2023-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=256, unique=True, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ky',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='название'),
        ),
    ]
