# Generated by Django 4.2 on 2023-07-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_content_en_post_content_ky_post_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
