# Generated by Django 4.2 on 2023-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_title_alter_post_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='post_images', verbose_name='картинка 1800х830px'),
        ),
    ]
