# Generated by Django 4.2 on 2023-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_description_post_sub_title_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title_ky',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='подзоголовок'),
        ),
    ]
