# Generated by Django 4.2 on 2023-07-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrafields',
            options={'verbose_name': 'Экстра картинки', 'verbose_name_plural': 'Экстра картинки'},
        ),
        migrations.RemoveField(
            model_name='extrafields',
            name='description',
        ),
        migrations.RemoveField(
            model_name='extrafields',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='extrafields',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='extrafields',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='extrafields',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='extrafields',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='extrafields',
            name='sub_title_ky',
        ),
        migrations.RemoveField(
            model_name='extrafields',
            name='sub_title_ru',
        ),
        migrations.AlterField(
            model_name='extrafields',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extrafields', to='history.history'),
        ),
        migrations.AlterField(
            model_name='history',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='company.company', verbose_name='компания'),
        ),
    ]
