# Generated by Django 4.2 on 2023-06-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafields',
            name='mission',
        ),
        migrations.AddField(
            model_name='extrafields',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extrafields', to='history.history'),
        ),
        migrations.AlterField(
            model_name='extrafields',
            name='sub_title',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок'),
        ),
    ]
