# Generated by Django 4.2 on 2023-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_extrafields_mission_extrafields_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafields',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='extrafields',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='extrafields',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='extrafields',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='extrafields',
            name='sub_title_ky',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='extrafields',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='history',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='history',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='history',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=996, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='sub_title_ky',
            field=models.CharField(blank=True, max_length=996, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=996, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='title_en',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='title_ky',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='title_ru',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
    ]
