# Generated by Django 4.2 on 2023-07-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('history', '0002_alter_extrafields_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='company.company', verbose_name='компания'),
        ),
    ]
