# Generated by Django 4.2 on 2023-08-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_history_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='history_images', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='history',
            name='main_picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='history_images', verbose_name='главная фотография'),
        ),
    ]
