# Generated by Django 4.2 on 2023-08-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_remove_history_company_history_description_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='description_other_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='history',
            name='description_other_ky',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='history',
            name='description_other_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='history',
            name='title_other_en',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='title_other_ky',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='title_other_ru',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='заголовок'),
        ),
    ]
