# Generated by Django 4.2 on 2023-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_history_description_other_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='history_images', verbose_name='фотография 350х420px'),
        ),
        migrations.AlterField(
            model_name='history',
            name='main_picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='history_images', verbose_name='фотография 2000x840px'),
        ),
    ]
