# Generated by Django 4.2 on 2023-06-29 15:41

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='фото/видео')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='год')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='line.line', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
