# Generated by Django 4.2 on 2023-08-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='line_images', verbose_name='фотография проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='project_images', verbose_name='фотография'),
        ),
    ]
