# Generated by Django 4.2 on 2023-08-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_extrafields_picture_alter_project_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='file',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='project',
            name='picture_other',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='project_images', verbose_name='фотография'),
        ),
    ]
