# Generated by Django 4.2 on 2023-06-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='project_images', verbose_name='фотография'),
        ),
    ]
