# Generated by Django 4.2 on 2023-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_file_project_picture_project_picture_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_other',
            field=models.TextField(blank=True, null=True, verbose_name='доп. описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_title',
            field=models.CharField(blank=True, max_length=265, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AlterField(
            model_name='extrafields',
            name='picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='line_images 350х420px', verbose_name='доп.фотографии для карусели'),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='project_images', verbose_name='фотография слева'),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture_other',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='project_images', verbose_name='фотография справа  300x720px'),
        ),
    ]
