# Generated by Django 4.2 on 2023-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_description_other_project_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_other_en',
            field=models.TextField(blank=True, null=True, verbose_name='доп. описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_other_ky',
            field=models.TextField(blank=True, null=True, verbose_name='доп. описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_other_ru',
            field=models.TextField(blank=True, null=True, verbose_name='доп. описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=265, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_title_ky',
            field=models.CharField(blank=True, max_length=265, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=265, null=True, verbose_name='подзоголовок'),
        ),
    ]
