# Generated by Django 4.2 on 2023-07-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_description_en_project_description_ky_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name_ky',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name_ru',
            new_name='title_ru',
        ),
    ]
