# Generated by Django 4.2 on 2023-07-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_name_project_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='line_images', verbose_name='фотография проекта')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrafields', to='project.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'экстра поле',
                'verbose_name_plural': 'экстра поля',
            },
        ),
    ]
