# Generated by Django 4.2 on 2023-06-30 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('email', models.EmailField(max_length=256, verbose_name='Эл.почта')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='номер должен начинаться на +996 и еще 9 цифр', regex='^\\+?996?\\d{9}$')])),
                ('question', models.TextField(verbose_name='вопрос')),
            ],
        ),
    ]
