# Generated by Django 4.2 on 2023-07-25 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('email', models.EmailField(max_length=256, verbose_name='Эл.почта')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='номер должен начинаться на +996 и еще 9 цифр', regex='^\\+?996?\\d{9}$')], verbose_name='номер телефона')),
                ('question', models.TextField(verbose_name='ваш вопрос')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
