# Generated by Django 4.2 on 2023-06-30 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_mail_options_alter_mail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='номер должен начинаться на +996 и еще 9 цифр', regex='^\\+?996?\\d{9}$')], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='question',
            field=models.TextField(verbose_name='ваш вопрос'),
        ),
    ]
