# Generated by Django 4.2 on 2023-08-11 06:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='main_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='видео 2000х700px'),
        ),
    ]
