# Generated by Django 4.2 on 2023-06-29 15:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_main_options_alter_main_main_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='main_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='видео'),
        ),
    ]
