# Generated by Django 4.2 on 2023-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_main_main_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='subtitle',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='main',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
    ]
