# Generated by Django 4.2 on 2023-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_subtitle_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='description_en',
            field=models.TextField(default='Комплексный инжиниринг в Кыргызской Республике', null=True, verbose_name='лозунг'),
        ),
        migrations.AddField(
            model_name='main',
            name='description_ky',
            field=models.TextField(default='Комплексный инжиниринг в Кыргызской Республике', null=True, verbose_name='лозунг'),
        ),
        migrations.AddField(
            model_name='main',
            name='description_ru',
            field=models.TextField(default='Комплексный инжиниринг в Кыргызской Республике', null=True, verbose_name='лозунг'),
        ),
        migrations.AddField(
            model_name='main',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='main',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='main',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='main',
            name='title_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='main',
            name='title_ky',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='main',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='название'),
        ),
    ]
