# Generated by Django 4.2 on 2023-06-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_description_en_main_description_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='main',
            name='text_ky',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='main',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
    ]
