# Generated by Django 4.2 on 2023-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='название')),
                ('title_ru', models.CharField(max_length=256, null=True, unique=True, verbose_name='название')),
                ('title_ky', models.CharField(max_length=256, null=True, unique=True, verbose_name='название')),
                ('title_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='название')),
                ('subtitle', models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок')),
                ('subtitle_ky', models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок')),
                ('description', models.TextField(verbose_name='текст')),
                ('description_ru', models.TextField(null=True, verbose_name='текст')),
                ('description_ky', models.TextField(null=True, verbose_name='текст')),
                ('description_en', models.TextField(null=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Cтраница о нас',
                'verbose_name_plural': 'Cтраница о нас',
            },
        ),
    ]
