# Generated by Django 4.2 on 2023-08-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='фотография'),
        ),
    ]
