# Generated by Django 4.2 on 2023-07-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_ru',
        ),
    ]
