# Generated by Django 4.2 on 2023-08-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_aboutus_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='about_us_image', verbose_name='фотография'),
        ),
    ]
