# Generated by Django 4.2 on 2023-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_aboutus_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_other',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='subtitle_other',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='about_us_image', verbose_name='фотография 2000x840px'),
        ),
    ]
