# Generated by Django 4.2 on 2023-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_aboutus_description_other_aboutus_subtitle_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_other_en',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_other_ky',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_other_ru',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='subtitle_other_en',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='subtitle_other_ky',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='subtitle_other_ru',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='подзоголовок'),
        ),
    ]
