# Generated by Django 4.2 on 2023-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='line_images', verbose_name='фотография направления'),
        ),
        migrations.AlterField(
            model_name='line',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='line_images', verbose_name='фотография направления'),
        ),
    ]
