# Generated by Django 4.2 on 2023-08-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafields',
            name='second_picture',
            field=models.ImageField(blank=True, null=True, upload_to='line_images', verbose_name='вторая фотография'),
        ),
        migrations.AlterField(
            model_name='extrafields',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='line_images', verbose_name='первая фотография'),
        ),
    ]
