# Generated by Django 4.2 on 2023-08-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_alter_extrafields_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_extrafields', to='line.line', verbose_name='направление'),
        ),
    ]
