# Generated by Django 4.2 on 2023-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_alter_extrafields_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='sub_title',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок'),
        ),
    ]
