# Generated by Django 4.2 on 2023-08-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0004_alter_extrafields_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='company',
        ),
    ]
