# Generated by Django 4.2 on 2023-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0005_remove_line_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='line_images', verbose_name='фотография 1024x800px'),
        ),
        migrations.AlterField(
            model_name='extrafields',
            name='second_picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='line_images', verbose_name='вторая фотография 1024x800px'),
        ),
        migrations.AlterField(
            model_name='line',
            name='main_picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='line_images', verbose_name='главная фотография 1024x800px'),
        ),
    ]
