# Generated by Django 4.2 on 2023-09-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_alter_extrafields_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrafields',
            options={'verbose_name': 'подробная информация', 'verbose_name_plural': 'подробная информация'},
        ),
    ]
