# Generated by Django 4.2 on 2023-06-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'партнер', 'verbose_name_plural': 'партнеры'},
        ),
        migrations.AlterModelOptions(
            name='partnerpage',
            options={'verbose_name': 'страница партнеров', 'verbose_name_plural': 'страница партнеров'},
        ),
    ]
