# Generated by Django 4.2 on 2023-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_partner_main_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
