# Generated by Django 4.2 on 2023-08-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companyimage_image'),
        ('partner', '0003_partner_description_en_partner_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_company', to='company.company', verbose_name='компания'),
        ),
    ]
