# Generated by Django 4.2 on 2023-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_alter_partner_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ky',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='sub_title_en',
            field=models.CharField(max_length=996, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='sub_title_ky',
            field=models.CharField(max_length=996, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='sub_title_ru',
            field=models.CharField(max_length=996, null=True, verbose_name='подзаголовок'),
        ),
    ]
