# Generated by Django 4.2 on 2023-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_remove_partner_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='picture_other',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='line_images', verbose_name='доп. фотография 250х250px'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='picture_other',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='line_images', verbose_name='доп. фотография'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='main_picture',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='line_images', verbose_name='главная фотография 250х250px'),
        ),
    ]
