# Generated by Django 4.2 on 2023-07-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_description_en_company_description_ky_and_more'),
        ('partner', '0006_partner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='company.company', verbose_name='компания'),
            preserve_default=False,
        ),
    ]
