# Generated by Django 4.2 on 2023-09-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0007_alter_extrafields_options'),
        ('vacancy', '0003_remove_vacancy_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='main_picture',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='должность'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_line', to='line.line', verbose_name='направление'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
