# Generated by Django 4.2 on 2023-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='career',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='career',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='career',
            name='title_en',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='career',
            name='title_ky',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='career',
            name='title_ru',
            field=models.CharField(max_length=556, null=True, verbose_name='заголовок'),
        ),
    ]
