# Generated by Django 4.2 on 2023-08-11 06:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='main_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='видео 2000х700px'),
        ),
        migrations.AlterField(
            model_name='careerimages',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='career_images', verbose_name='фотография 350х420px'),
        ),
    ]
