# Generated by Django 4.2 on 2023-07-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=556, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=556, null=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(max_length=556, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=556, null=True, verbose_name='заголовок')),
                ('sub_title', models.CharField(max_length=996, verbose_name='подзаголовок')),
                ('sub_title_ru', models.CharField(max_length=996, null=True, verbose_name='подзаголовок')),
                ('sub_title_ky', models.CharField(max_length=996, null=True, verbose_name='подзаголовок')),
                ('sub_title_en', models.CharField(max_length=996, null=True, verbose_name='подзаголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('description_ru', models.TextField(null=True, verbose_name='описание')),
                ('description_ky', models.TextField(null=True, verbose_name='описание')),
                ('description_en', models.TextField(null=True, verbose_name='описание')),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='line_images', verbose_name='главная фотография')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='company.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'миссия',
                'verbose_name_plural': 'миссии',
            },
        ),
        migrations.CreateModel(
            name='ExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок')),
                ('sub_title_ru', models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок')),
                ('sub_title_ky', models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок')),
                ('sub_title_en', models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='mission_images', verbose_name='фотография миссии')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrafields', to='mission.mission', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'экстра поле',
                'verbose_name_plural': 'экстра поля',
            },
        ),
    ]
