# Generated by Django 4.2 on 2023-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='sub_title',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='подзаголовок'),
        ),
    ]
