# Generated by Django 4.2 on 2023-08-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_mission_main_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='company',
        ),
    ]
